### ISSUE TITLE
Can't migrate db from glitch-soc: column settings.thing_type does not exist

### ISSUE THREAD

**Issue by cdn0x12** [TheEssem/mastodon#32]
### Steps to reproduce the problem

1. Setup a glitch-soc instance using nightly 2024-12-28 or later
2. switch to chuckya codebase
3. run db migration

### Expected behaviour

The glitch-soc to chuckya db migration was successful

### Actual behaviour

The glitch-soc to chuckya db migration was unsuccessful

Logs attached to "Detailed description"

### Detailed description

```
mastodon@5e455b572174:~$ RAILS_ENV=production SKIP_POST_DEPLOYMENT_MIGRATIONS=true bundle exec rails db:migrate
I, [2024-12-29T01:10:40.115745 #17]  INFO -- : Migrating to MoveEmojiReactionSettings (20230215074425)
== 20230215074425 MoveEmojiReactionSettings: migrating ========================
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:23:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:23:in `up'

Caused by:
PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist (PG::UndefinedColumn)
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:24:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:23:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### Mastodon instance

mstdn.owu.one

### Mastodon version

v4.4.0-nightly.2024-12-28+glitch

### Environment

Docket container

**Comment by TheEssem** [comment]
Should (hopefully) be fixed with 6cf96f16e114a5660538c26dbbc0ad8de59c7e2c

**Comment by cdn0x12** [comment]
I tried re-initiating the migration by mounting the patched migration file and rebuilt the image. Seems that the error still exists.


```
# To verify the migration file is indeed changed
mastodon@f9f0cfb3fda5:~$ cat db/migrate/20230215074425_move_emoji_reaction_settings.rb | grep "HashWithIndifferentAccess, Symbol"
      YAML.safe_load(self[:value], permitted_classes: [ActiveSupport::HashWithIndifferentAccess, Symbol]) if self[:value].present?
```

```
# re-run the migration
mastodon@f9f0cfb3fda5:~$ RAILS_ENV=production SKIP_POST_DEPLOYMENT_MIGRATIONS=true bundle exec rails db:migrate
I, [2024-12-29T06:43:28.356871 #74]  INFO -- : Migrating to MoveEmojiReactionSettings (20230215074425)
== 20230215074425 MoveEmojiReactionSettings: migrating ========================
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:21:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:21:in `up'

Caused by:
PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist (PG::UndefinedColumn)
LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
                                                  ^
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `group_by'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:22:in `block in up'
/opt/mastodon/db/migrate/20230215074425_move_emoji_reaction_settings.rb:21:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by TheEssem** [comment]
Odd; will look into it once I get the chance.

**Comment by TheEssem** [comment]
Very late, but this should now be fixed for real with dd19259453659137ccef13144552e613ec3b943e.
